{{- if and (not .Values.existingSecret.name) .Values.bouncerKey (ne .Values.bouncerKey "change-me") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crowdsec-firewall-bouncer.name" . }}-key
  labels:
    {{- include "crowdsec-firewall-bouncer.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.bouncerKey }}
{{- end }}
